### ISSUE TITLE
Windows CI is broken

### ISSUE THREAD

**Issue by N-Coder** [ogdf/ogdf#104]
The CI is currently failing on Windows, which currently affects all PRs. The last working job is [here](https://github.com/ogdf/ogdf/actions/runs/6532428294/job/17735831322) and the first failing job is [here](https://github.com/ogdf/ogdf/actions/runs/6574156644/job/17892649012). Between those two, the windows-2022 runner image was updated from 20231002.1.0 to 20231016.1.0 which seemingly leads to ccache no longer being installed by the respective action. This is despite that actions is still exactly the same version and the runner image [change notes](https://github.com/actions/runner-images/commit/32c795e64ca31dded26ab79c86bd9e3a6d542d74) mention no major or relevant changes. Unfortunately, the runner images are not available publicly for [legal reasons](https://github.com/actions/runner-images/issues/176).

**Comment by milsen** [comment]
The runner image 20231016.1.0 already contains ccache 4.8.1 in C:\Strawberry\c\bin\ccache.exe . Hence, it is not installed by the ccache-action, but the pre-installed ccache seems to be faulty in some way and does not work.

The runner image 20231023.1.0, however, does not have ccache pre-installed (which should make the builds succeed again), so maybe we can hope that the problem just disappears once all builds are executed with 20231023.1.0+.

**Comment by N-Coder** [comment]
Ah, thanks for debugging this further! I just re-ran all recent jobs and it seems they all already got the newer images and Windows is now working again properly, so I'm closing this.
