### ISSUE TITLE
tr/tuple clang

### ISSUE THREAD

**Issue by saeschdivara** [ogdf/ogdf#11]
Hey,

I have the problem that on my OS X, my clang compiler doesn't support tr/tuple so I had to insert the following line (though my solution isn't perfect yet):
GTEST_USE_OWN_TR1_TUPLE 1

in the following header file: ogdf/test/gtest/gtest.h

```c++
#ifndef GTEST_INCLUDE_GTEST_GTEST_H_
#define GTEST_INCLUDE_GTEST_GTEST_H_

#define GTEST_USE_OWN_TR1_TUPLE 1

#include <limits>
#include <vector>
```

**Comment by schulzch** [comment]
You should add this define to the build system, e.g.:
```
if("${CMAKE_SYSTEM_NAME}" MATCHES "Darwin")
  if(${CMAKE_SYSTEM_VERSION} MATCHES "todo-some-number-here")
       add_definitions("-DGTEST_USE_OWN_TR1_TUPLE=1")
  endif()
endif()
```
Adding `-std=c++11` to Clang's command line should also fix the problem, as `<tuple>` is part of C++11.
