### ISSUE TITLE
Installing ogdf for Bandage

### ISSUE THREAD

**Issue by joseale2310** [ogdf/ogdf#13]
Hi!

I am trying to install Bandage (https://github.com/rrwick/Bandage). In its README file it says that I need to download and install the OGDF code (2012.07 Sakura release), but I cannot find it! I have tried with you last release, but it seems that it doesn't work. Where can I find that repository?

Many thanks,

Alex.

**Comment by TiloW** [comment]
Hi Alex,

please take a look at the [version history on ogdf.net](http://www.ogdf.net/doku.php/tech:versions) or simply checkout the initial commit of this repo (f0a0f79).
