### ISSUE TITLE
Unable to compile OGDF on Visual Studio because of IsNull function in snowhouse subproject

### ISSUE THREAD

**Issue by wisk** [ogdf/ogdf#17]
Hello,

I just created a issue [here](https://github.com/joakimkarlsson/snowhouse/issues/17) to notify snowhouse authors that `IsNull` function can't be compiled under Visual Studio because of how the code tests if `nullptr` is available.
Because of this issue, OGDF can't be compiled under Visual Studio.
I hope it could help.

**Comment by TiloW** [comment]
The snowhouse issue is closed by now and we are running Visual Studio 2015 builds just fine on our CI servers.

Does this still happen to you with the current snapshot?

**Comment by sbeyer** [comment]
I believe that this is fixed now, at least by the latest snapshot commit acd58c7
