### ISSUE TITLE
Node- and EdgeArrays vs. std::vector

### ISSUE THREAD

**Issue by milsen** [ogdf/ogdf#177]
In GitLab by @ogdf-gitlab-jschmidt on Feb 12, 2019, 15:14

When looking at the efficient C-code from the nauty package by McCay, I observed that OGDF is (necessarily) slower and tried to pin down the parts causing that. What I did not expect is that Edge- and NodeArrays seem to be somewhat slow, even compared to std::vector. The following is a simple test (hope everything is correctly initialized), where #if=1 needs twice as long as #if=0 (even worse with NodeArrays). Since almost every algorithm uses these arrays, wouldn't OGDF more performant if they build upon std::vector then (on edge and node ids)?

```
#include <ogdf/basic/graph_generators/randomized.h>

using namespace std;
using namespace ogdf;

int main(int argc, char* argv[]) {
	InputGraphInterface input(argc, argv);
	Graph G;
	randomSimpleConnectedGraph(G, 20, 40);
	for (int i = 0; i < 100000000; i++) {

#if 1
		EdgeArray<int> edgeArray(G, 0);
		//NodeArray<NodeArray<int> > matrix(G, NodeArray<int>(G, 0));
#else
		vector<int> evec(G.numberOfEdges(),0);
		//vector<vector<int> > nvec(G.numberOfNodes(), vector<int>(G.numberOfNodes(), 0));
#endif
	}

	return 0;
}
```

**Comment by milsen** [comment]
I discussed this with Markus and he agrees that in general, `Array` and similar classes (like `ArrayBuffer`)  can be replaced by `std::vector`. Their usage is a relic from a time when the stdlib was much slower and it was beneficial to implement your own data structures.  
Hence `NodeArray`, `EdgeArray` etc. should probably inherit from `std::vector` rather than `Array`.

Note: This may not hold for e. g. `List` -- it might still be faster than `std::list` since the memory allocator of the OGDF allows for a very fast allocation of small memory blocks (e. g. for list elements) that is probably not possible with the stdlib.

**Comment by milsen** [comment]
In GitLab by @N-Coder on Sep 15, 2020, 13:36

I've two different issues on GitHub [[1](https://github.com/ogdf/ogdf/issues/56#issuecomment-653641917), [2](https://github.com/ogdf/ogdf/issues/53)], both caused by how the current Array-based implementation uses default values and initializes its data. Using a vector-based `NodeArray` would easily resolve both while also providing a nicer interface (like less surprising initialization plus easy usage of all std algorithms, traits, iterators etc.) and more efficiency (better compiler optimizations and stuff like automatically using bit-vectors for boolean arrays).

One of my data structures also needed something similar to a `NodeArray`, having a dynamically growing number of int-indexed Elements which should be labelled, but without being backed by any Graph. Having a look at how OGDF does this, I found out that `AdjEntryArray`, `ClusterArray`, `EdgeArray`, `FaceArray` and `NodeArray` are all replicating this functionality without sharing any code (except for using `ogdf::Array` as parent). I extracted all that common functionality into a [template class](https://git.tcs.uos.de/snippets/17), which could be easily migrated to `std::vector` and then used as basis for all other label arrays, which would then need far less custom code.

Regarding the element allocation for `List`, I guess that standard C++ now also has a concept for customizing this, called [`AllocatorAwareContainer`](https://en.cppreference.com/w/cpp/named_req/AllocatorAwareContainer). All standard library containers except `std::array` (but especially including `vector` and `list`) are `AllocatorAwareContainers` that take a [`allocator`](https://en.cppreference.com/w/cpp/memory/allocator) parameter to their [constructors](https://en.cppreference.com/w/cpp/container/list/list) which allows providing custom `allocate` and `deallocate` functions.

I believe that OGDF could significantly benefit from relying more on the stdlib and more streamlined containers, so I'd be happy to help moving in this direction.

**Comment by milsen** [comment]
In GitLab by @N-Coder on Sep 22, 2020, 13:31

Note: isocpp.org has some interesting FAQ entries on [placement-new](https://isocpp.org/wiki/faq/dtors#placement-new) and [memory pools](https://isocpp.org/wiki/faq/dtors#memory-pools). They include the warning that, when using these methods (which might be suitable when allocating many small objects), you need to take care of [alignment](https://en.cppreference.com/w/c/language/object#Alignment) yourself.

Regular `std::malloc` aligns memory suitable for any object type (which, in practice, means that it is aligned to `alignof(std::max_align_t)`), for details and how to customize that see [`std::aligned_alloc`](https://en.cppreference.com/w/cpp/memory/c/aligned_alloc).
As an alternative, one could use [`alignof`](https://en.cppreference.com/w/cpp/language/alignof) and then use [`std::align`](https://en.cppreference.com/w/cpp/memory/align) to generate exactly aligned pointers.

So I guess that when using [`MallocMemoryAllocator::allocate(nBytes)`](https://git.tcs.uos.de/ogdf-devs/OGDF/-/blob/master/include/ogdf/basic/memory/MallocMemoryAllocator.h#L59) together with the overridden [`static void *operator new(size_t)`](https://git.tcs.uos.de/ogdf-devs/OGDF/-/blob/master/include/ogdf/basic/memory.h#L54), that still does the "right thing", as the `malloc`ed memory is always aligned to something like 8 or 16 bytes (`std::max_align_t` is usually synonymous with the largest scalar type, which is `long double` on most platforms, and its alignment requirement is either 8 or 16).

As far as I understood the code, [`PoolMemoryAllocator`](https://git.tcs.uos.de/ogdf-devs/OGDF/-/blob/master/src/ogdf/basic/memory/PoolMemoryAllocator.cpp) in contrast does the following:
Its `static MemElemPtr s_tp[TABLE_SIZE]` is a table with 256 entries, each entry pointing to the start of a singly-linked list of memory slices of the respective size.
If available, [`PoolMemoryAllocator::allocate(size_t)`](https://git.tcs.uos.de/ogdf-devs/OGDF/-/blob/master/src/ogdf/basic/memory/PoolMemoryAllocator.cpp#L79) simply pops off the first of these slices and hands it out.
Otherwise, it calls `fillPool` to generate new adequately-sized slices in the respective row of the table, where the following code is relevant:
```cpp
int nWords;
int nSlices = slicesPerBlock(max(nBytes,(uint16_t)MIN_BYTES),nWords);
// internally calculates does the following:
//	nWords = (nBytes + OGDF_SIZEOF_POINTER - 1) / OGDF_SIZEOF_POINTER;
//	return (BLOCK_SIZE - OGDF_SIZEOF_POINTER) / (nWords * OGDF_SIZEOF_POINTER);

pFreeBytes = allocateBlock();
// basically does malloc(BLOCK_SIZE), returning max-aligned memory

makeSlices(pFreeBytes, nWords, nSlices);
// does the following:
//	do {
//		pBlock = pBlock->m_next = pBlock+nWords;
//	} while(--nSlices > 1);
//	pBlock->m_next = nullptr;
```
To me, that looks as if the slicing doesn't care about alignment at all, but just cuts the memory into equally sized chunks (no matter where those chunks begin).
If you now allocate some object in one of these slices, its fields won't be aligned in memory in most of the cases.
I don't know how bad this gets in practice, but I guess all that alignment-stuff in the stdlib and by the compiler is done for a reason, e.g. the CPU being able to work a lot better/faster with memory-aligned multi-byte values.

So by now I'm not quite sure how much performance improvement the custom-made allocators actually provide.
If OGDF were to migrate to stdlib's containers and allocators, we could simply use one of the [many](https://github.com/topics/pool-allocator) [publicly](https://gcc.gnu.org/onlinedocs/libstdc++/manual/memory.html#allocator.ext) [available](https://stackoverflow.com/questions/25069570/very-fast-object-allocator-for-small-object-of-same-size) (and often GPL-compatible header-only) pool-allocator implementations that are probably aware of that.
In any case, such performance optimizations should always go with actual evaluations checking for their necessity and effectiveness.

**Comment by milsen** [comment]
In GitLab by @sbeyer on Sep 22, 2020, 22:58

> If OGDF were to migrate to stdlib's containers and allocators, we could simply use one of the [many](https://github.com/topics/pool-allocator) [publicly](https://gcc.gnu.org/onlinedocs/libstdc++/manual/memory.html#allocator.ext) [available](https://stackoverflow.com/questions/25069570/very-fast-object-allocator-for-small-object-of-same-size) (and often GPL-compatible header-only) pool-allocator implementations that are probably aware of that.

There's also the `std::pmr` subnamespace that provides allocators for std containers. One problem is that it needs C++17 (switching to C++17 is relatively safe because all major compilers support C++17 to a great extent now, but that's another topic), and another problem is that it's relatively low-level and not-so-nice in its usage.

**Comment by milsen** [comment]
In GitLab by @N-Coder on Jan 12, 2021, 17:44

Note: [`cheaper`](https://github.com/emeryberger/cheaper) seems like a nice tool to automatically search for usage patterns that might benefit from a custom heap. The prof behind that repo seems to be doing a lot of [interesting stuff](https://github.com/plasma-umass/memory-landscape) about memory management.

**Comment by N-Coder** [comment]
#101 replaces the `Array` part of `NodeArray` and the like with `std::vector` and thus closes this. Still, thinking more about the way the OGDF allocates memory might be a good idea.
