### ISSUE TITLE
cplex.h: No such file or directory

### ISSUE THREAD

**Issue by TheComet93** [ogdf/ogdf#21]
I'm trying to compile this on linux and I'm running into this error message. Where is cplex.h coming from? There was no mention of it in the documentation of OGDF nor are there any build checks in any of the CMake scripts.

**Comment by TiloW** [comment]
You have probably set `COIN_SOLVER` to `CPX` instead of the default `CLP`in your cmake configuration.

**Comment by TheComet93** [comment]
Ah, you are right! Thanks, now it compiles fine.
