### ISSUE TITLE
planar/planarization layout with fixed node positions

### ISSUE THREAD

**Issue by ziyuezzy** [ogdf/ogdf#229]
Dear all,

I wonder if there is a way to fix node positions when doing planar/planarization layout.

The attribute of the input graph is constructed such that the positions of the nodes are specified. When calling a planarization  layout algorithm (for example, planarizaitoin+orthogonal layout) on this graph, the position of the nodes in the graph attributes will be deleted/ignored. Therefore the resulting layout will have an optimized number of crossings, but with different node positions compared to the specified positions of the nodes. 
I understand that this is probably necessary for the planarization algorithms, but is there a trick of post-processing or mix-layout-method such that (1) the positions of the nodes from the graph attributes are kept (2) the crossing information from the layout algorithm is kept?

Best regards,
Z.

**Comment by milsen** [comment]
I don't think there is a layout algorithm that has this option (only `StressMinimization` seems to allow for fixing the coordinates, but that algorithm does not try to minimize crossings).

The closest idea to emulate this functionality is this:
You can compute a planarization (i.e. via the `SubgraphPlanarizer`), i.e. a planar representation of the graph where crossings are represented by dummy vertices of degree 4. Then you can use `planarEmbed` on the planarization to obtain an embedding, i.e. a specific ordering of adjacency entries around each node. From a graph-theoretic point of view, the embedding guarantees that the planarization can be drawn without any new additional crossings regardless of the node coordinates. So you could just place the original graph nodes where you want to have them (and even set the dummy vertices to random positions if you want to), and there should exist some routing of the edges such that no additional crossings are produced. However, finding the correct positions for the edge bends may not be easy (you'd have to do this manually) and the final product may not look very good even though it contains no additional crossings...

**Comment by ziyuezzy** [comment]
Hi Milsen,

Thanks for the reply, much appreciated. Indeed dummy nodes with degree=4 can be added in the graph in order to keep the number of crossings. 

What about planar graph that do not necessarily have any crossing? Do you have any idea to draw a planar graph with fixed nodes' positions while avoid any crossing?

best regards,
Ziyue.

**Comment by milsen** [comment]
You're welcome!

> Do you have any idea to draw a planar graph with fixed nodes' positions while avoid any crossing?

Sadly, I do not. (If I did, a method to draw non-planar graphs with fixed node positions would directly follow by using a planarization.)
