### ISSUE TITLE
`GraphConstIterator` Compiling error on master branch

### ISSUE THREAD

**Issue by felixf4xu** [ogdf/ogdf#243]
Hi,

when I compile the project, I have this error:
>ogdf/include/ogdf/basic/Graph_d.h:109:45: error: 'GraphConstIterator' is not a member of 'ogdf::internal'; did you mean 'GraphIterator'?
  109 | OGDF_CHECK_CONCEPT(OGDF_NODE_ITER<internal::GraphConstIterator<node>>);
      |                                             ^~~~~~~~~~~~~~~~~~
      |                                             GraphIterator

I searched the code
```c++
OGDF_CHECK_CONCEPT(OGDF_EDGE_ITER<internal::GraphConstIterator<edge>>);
```
`GraphConstIterator` is actually not declared anywhere. Is it an obvious bug?

**Comment by milsen** [comment]
Yes, it is. Good find!
 
`GraphConstIterator` was removed in c1047f24a44e982ab12c4920886239abbdc2b7ab after [this discussion](https://github.com/ogdf/ogdf/pull/101#discussion_r146608461). We can probably just remove those two lines that contain `OGDF_CHECK_CONCEPT(... GraphConstIterator ...)`.

**Comment by felixf4xu** [comment]
Thanks, PR #245 is created for review
