### ISSUE TITLE
Consider licensing under LGPL

### ISSUE THREAD

**Issue by arthur-tacca** [ogdf/ogdf#26]
It seems a pity that OGDF is licensed under the GPL. I realise there are good arguments for releasing it under this license, but it certainly restricts who can use the library. I would suggest that something like the LGPL, which would allow its use by many more people but still protect the library.

I'm sure this has been discussed internally, but I thought it would be good to at least raise it in public. (It was mentioned in #20, but that issue was really about something else.)

By the way, it seems to me that OGDF actually already is LGPLed, perhaps by accident. According to [the license page](http://amber-v7.cs.tu-dortmund.de/doku.php/tech:license), the combination of OGDF QML plugin + OGDF library is LGPL:

>  Moreover, we grant a special exception to the OGDF QML plugin by Christoph Schulz (licensed under the GNU Lesser General Public License) for linking OGDF and distributing the plugin under LGPL v2 or v3.

But according to the terms of the LGPL, any portion of LGPL software may be modified and re-released under the same license. Indeed, that is the whole point of the GNU licenses. So I could modify (OGDF QML plugin + OGDF library) by removing the OGDF QML plugin part, and *boom* we have OGDF library on its own under LGPL. But I am not a lawyer, so some clarity would be good.

**Comment by sbeyer** [comment]
The QML plugin exception is granted for *linking* OGDF and *distributing* the plugin with linked OGDF. OGDF itself does not become LGPL; OGDF is not considered to be *a portion* of the QML plugin. Also the exception is not granted for any fork of the QML plugin, only for the version by Christoph Schulz.

Also we do not intend to release the OGDF under any other license than the GPL (with the added exceptions).

(Disclaimer: I am not responsible for the licensing of OGDF nor do I care much but I reproduce what our project manager said in a discussion.)

**Comment by arthur-tacca** [comment]
Hmm, when I wrote that paragraph I was thinking as if the plugin's LGPL has to also apply to the OGDF when linked against it. But of course, that type of "infection" only applies to the GPL, not the LGPL; to paraphrase myself, that is the whole point of the LGPL.

Thanks for the clarification, and passing on the project manager's comment.
