### ISSUE TITLE
Can not build in debug mode, due to issue in CoinOslFactorization2.cpp

### ISSUE THREAD

**Issue by emmenlau** [ogdf/ogdf#29]
When I build with `DEBUG` defined, I get an error:
```
/data/ogdf-snapshot-2017-07-23/src/coin/CoinUtils/CoinOslFactorization2.cpp: In function 'int c_ekkbtrn_mpt(const EKKfactinfo*, double*, int*, int, int*)':
/data/ogdf-snapshot-2017-07-23/src/coin/CoinUtils/CoinOslFactorization2.cpp:1470:7: error: redeclaration of 'int i'
   int i;
       ^
/data/ogdf-snapshot-2017-07-23/src/coin/CoinUtils/CoinOslFactorization2.cpp:1457:7: note: 'int i' previously declared here
   int i;
       ^
```

**Comment by sbeyer** [comment]
Can you elaborate how you build OGDF?

**Comment by emmenlau** [comment]
If you check the code, there is a small bug: if `DEBUG` is defined, then there is a duplicate definition of `int i`.

**Comment by TiloW** [comment]
Note that even though we don't consider duplicate definitions to be good practice, c++ still allows this.

We do enable compile flags to prevent duplicate definitions in the OGDF.
However, we are not the maintainers of the included COIN library and hence cannot enforce our coding standards for these files.

So - how did you try to build?

**Comment by emmenlau** [comment]
Hmm, I see! Should I report this upstream to Coin? Can you point me to the correct group?

My build is a bit special so I understand that this is a problem triggered specifically by my build,
not by officially supported flags. I define `DEBUG` manually in CFLAGS and CXXFLAGS, which
seems to trigger this issue. However I did *not* set -Werror or anything like it.

I build ogdf with a git snapshot from `2017-07-23` using cmake. I'm maintaining a CI system that
builds for Linux, Windows and MacOS, in debug and release mode. For the debug mode, I set
specific compiler flags in CFLAGS, CXXFLAGS and LDFLAGS:
```
export CPPFLAGS="${CPPFLAGS} -DDEBUG"
export CFLAGS="${CFLAGS} -fPIC -ggdb3 -O0 -m64 -march=nehalem -mtune=haswell ${CPPFLAGS}"
export CXXFLAGS="${CXXFLAGS} -fPIC -ggdb3 -O0 -m64 -march=nehalem -mtune=haswell ${CPPFLAGS}"
export LDFLAGS="${LDFLAGS} -m64"
```
Then I build with cmake:
```
cmake . \
    -Wno-dev \
    -G"Unix Makefiles" \
    -DCMAKE_PREFIX_PATH="/data" \
    -DCMAKE_INSTALL_PREFIX="/data" \
    -DCMAKE_BUILD_TYPE="Debug" \
    -DCMAKE_POSITION_INDEPENDENT_CODE="ON" \
    -DBUILD_SHARED_LIBS="ON" && \
make && \
make install
```

**Comment by TiloW** [comment]
I just checked the code and you're right: the error should arise whenever `DEBUG` is defined for COIN - independently of any compiler settings (I assumed this to be a nested re-definition, but it's the same scope). So this is a result of setting the `-DDEBUG` flag, as you already mentioned.

We are planning to update COIN but I can't give you any estimates on when that will be. If this bug is still not fixed in the most recent COIN version you might [report it to the COIN  developers](https://www.coin-or.org/contributing/).

**Comment by emmenlau** [comment]
Ok sounds good. I'm closing this issue for now, as the problem is sufficiently obscure to be not
immediately relevant.

**Comment by sbeyer** [comment]
> However I did not set -Werror or anything like it.

Note that you can turn off `-Werror` by disabling our cmake setting `OGDF_WARNING_ERRORS`. I however wonder why this affects COIN and not only OGDF.
