### ISSUE TITLE
Deterministic FMMM

### ISSUE THREAD

**Issue by giordi91** [ogdf/ogdf#33]
Good evening, first of all thanks a lot for the effort put in the library! It is really useful. I am currently using the energy method to layout a graph in this way.

`for (int i = 0; i < graph->m_edges.size(); ++i) {
    auto edge = graph->m_edges[i];
    auto nodeA = graphmap[edge.start];
    auto nodeB = graphmap[edge.end];
    g.newEdge(nodeA, nodeB);
  }

  ogdf::GraphAttributes GA(g);
  ogdf::FMMMLayout fmmm;

  fmmm.useHighLevelOptions(true);
  fmmm.unitEdgeLength(15.0);
  fmmm.newInitialPlacement(true);
  fmmm.call(GA);
`
I extract from my graph the topology and then execute the FMMM. I noticed that the graph is not deterministic, mainly I get overall reflections, rotations and some squashing. Some branches are more or less bent. Is there any way to try to fix this, (fixed seed) or limit that behaviour? Would give an initial position of the nodes help? or some other options?

here some different runs of the code:
![image](https://user-images.githubusercontent.com/2525797/34532493-9774c7dc-f0b6-11e7-8a87-00a1da5e3d9b.png)

![image](https://user-images.githubusercontent.com/2525797/34532501-9da4c134-f0b6-11e7-8c1d-27b6c8e86440.png)

![image](https://user-images.githubusercontent.com/2525797/34532507-a31af372-f0b6-11e7-9ad8-fc23bc26a790.png)

Best regards

M.

**Comment by sbeyer** [comment]
I think this was recently fixed in #25 ... do you use the latest master?

**Comment by giordi91** [comment]
Hi, I used the randomSeed and initialPlacmentForces call like the example and worked. Might be good to add it to the samples in the How to doc. 
Thanks
