### ISSUE TITLE
System-wide install

### ISSUE THREAD

**Issue by mimre25** [ogdf/ogdf#35]
Is there a way to install this system wide?

Even when I set the 
CMAKE_INSTALL_PREFIX             /usr/local 

it will still install in the current folder.

**Comment by sbeyer** [comment]
It is currently not supported. The pull requests #14 and #16 deal with this issue, and I am willing to add support for this for the next snapshot.

**Comment by sbeyer** [comment]
I think this is resolved by the latest snapshot.
