### ISSUE TITLE
CMake installs in noncanonical location

### ISSUE THREAD

**Issue by navidR** [ogdf/ogdf#42]
https://github.com/ogdf/ogdf/blob/master/cmake/ogdf.cmake#L169

This creates a lot of problems for tools using vcpkg. The problem is having `${CMAKE_LIBRARY_ARCHITECTURE}` in your install location. This would mean is installing itself in noncanonical locations. This should get removed immediately. For now, till it gets fixed upstream, I am using a custom patch for ogdf in [vcpkg](https://github.com/Microsoft/vcpkg/blob/master/ports/ogdf/portfile.cmake).

For example, look at this to see how the glog library handles install(export) : 
https://github.com/google/glog/blob/master/CMakeLists.txt#L674

```
diff --git a/cmake/coin.cmake b/cmake/coin.cmake
index b1329bf..a4eb84d 100644
--- a/cmake/coin.cmake
+++ b/cmake/coin.cmake
@@ -55,9 +55,9 @@ else()
 endif()
 
 # installation
-set(COIN_INSTALL_LIBRARY_DIR "lib/${CMAKE_LIBRARY_ARCHITECTURE}" CACHE PATH "Installation path of COIN library")
+set(COIN_INSTALL_LIBRARY_DIR "lib" CACHE PATH "Installation path of COIN library")
 set(COIN_INSTALL_INCLUDE_DIR "include" CACHE PATH "Installation path of COIN header files (creates subdirectory)")
-set(COIN_INSTALL_CMAKE_DIR "lib/${CMAKE_LIBRARY_ARCHITECTURE}/cmake/OGDF/" CACHE PATH "Installation path of COIN files for CMake")
+set(COIN_INSTALL_CMAKE_DIR "lib/cmake/OGDF/" CACHE PATH "Installation path of COIN files for CMake")
 mark_as_advanced(COIN_INSTALL_LIBRARY_DIR COIN_INSTALL_INCLUDE_DIR COIN_INSTALL_CMAKE_DIR)
 install(TARGETS COIN
   EXPORT CoinTargets
diff --git a/cmake/ogdf.cmake b/cmake/ogdf.cmake
index 7463d26..4602f15 100644
--- a/cmake/ogdf.cmake
+++ b/cmake/ogdf.cmake
@@ -166,9 +166,9 @@ if(SHOW_STACKTRACE)
 endif()
 
 # installation
-set(OGDF_INSTALL_LIBRARY_DIR "lib/${CMAKE_LIBRARY_ARCHITECTURE}" CACHE PATH "Installation path of OGDF library")
+set(OGDF_INSTALL_LIBRARY_DIR "lib" CACHE PATH "Installation path of OGDF library")
 set(OGDF_INSTALL_INCLUDE_DIR "include" CACHE PATH "Installation path of OGDF header files (creates subdirectory)")
-set(OGDF_INSTALL_CMAKE_DIR "lib/${CMAKE_LIBRARY_ARCHITECTURE}/cmake/OGDF/" CACHE PATH "Installation path of OGDF files for CMake")
+set(OGDF_INSTALL_CMAKE_DIR "lib/cmake/OGDF/" CACHE PATH "Installation path of OGDF files for CMake")
 mark_as_advanced(OGDF_INSTALL_LIBRARY_DIR OGDF_INSTALL_INCLUDE_DIR OGDF_INSTALL_CMAKE_DIR)
 configure_file(cmake/ogdf-config.cmake "${PROJECT_BINARY_DIR}/ogdf-config.cmake" @ONLY)
 install(TARGETS OGDF

```

**Comment by sbeyer** [comment]
Sorry for the very late reply. I see in your link that you have already pointed out yourself that you can simply configure the install paths without any patching. That's the whole point of declaring (and setting) these variables at this point.

BTW, I thought the path is canonical for multi-arch systems (it's also one of the standard search paths in CMake's find_package() function). And I thought multi-arch is the default in Linux distributions nowadays.
