### ISSUE TITLE
RadialTreeLayout generates non-planar Tree drawings

### ISSUE THREAD

**Issue by N-Coder** [ogdf/ogdf#52]
Consider the following example which loads a tree, calls RadialTreeLayout to determine node positions and renders the result as SVG:
```
#include <include/ogdf/basic/GraphAttributes.h>
#include <include/ogdf/tree/RadialTreeLayout.h>
#include <include/ogdf/fileformats/GraphIO.h>

int main() {
    std::stringstream ss;
    ss << "digraph G {\n"
          "\t0 -> 1\n"
          "\t1 -> 2\n"
          "\t2 -> 3\n"
          "\t2 -> 4\n"
          "\t4 -> 5\n"
          "\t4 -> 6\n"
          "\t1 -> 7\n"
          "\t7 -> 8\n"
          "\t7 -> 9\n"
          "\t1 -> 10\n"
          "\t0 -> 11\n"
//          "\t11 -> 12\n"
//          "\t11 -> 13\n"
//          "\t11 -> 14\n"
          "\t0 -> 15\n"
          "\t15 -> 16\n"
          "\t15 -> 17\n"
          "\t17 -> 18\n"
//          "\t17 -> 19\n"
          "\t15 -> 20\n"
//          "\t20 -> 21\n"
//          "\t20 -> 22\n"
//          "\t20 -> 23\n"
          "}";

    ogdf::Graph g;
    ogdf::GraphAttributes g_a(g, ogdf::GraphAttributes::all);
    ogdf::GraphIO::readDOT(g, ss);
    for (auto n:g.nodes) {
        std::stringstream ss;
        ss << n->index();
        g_a.label(n) = ss.str();
        g_a.fillColor(n) = ogdf::Color::Name::White;
    }

    ogdf::RadialTreeLayout rtl;
    rtl.call(g_a);

    std::ofstream os("testSVG.svg");
    ogdf::GraphIO::drawSVG(g_a, os);

    return 0;
}
```
Using OGDF 2020.02 (Catalpa), the output in this case is the following:
![testSVG](https://user-images.githubusercontent.com/1306276/78650084-b68c7880-78be-11ea-8786-1d91a2c73e7e.png)
The 12-16 edge needlessly crosses the 1-2 edge.

If you uncomment the lines adding children to nodes 11 and 17, you get the following drawing:
![testSVG](https://user-images.githubusercontent.com/1306276/78650015-9eb4f480-78be-11ea-8231-695522b0ca46.png)
The position for node 12 now overlaps the position of some other node.
Additionally, I would expect the parent to be centered above its children, which is obviously not the case for e.g. 7, 11, and 17. It looks a little as if the positions of children being off also causes all these layout issues. A lot of code in [RadialTreeLayout.cpp](https://github.com/ogdf/ogdf/blob/master/src/ogdf/tree/RadialTreeLayout.cpp) is commented out using `#if 0`, so it was pretty hard for me to understand what's going on and I couldn't pinpoint the possible (off-by-one?) error.

**Comment by sbeyer** [comment]
Thank you for reporting this issue. The `RadialTreeLayout` code is untouched (except for minor changes) for 8 years now and the original author is not an active OGDF developer any longer. Let's see if one of the current developers is willing to look at this issue.
