### ISSUE TITLE
NodeArray<C> requires a copy constructible value class C, so NodeArray<std::unique_ptr<T>> won't compile

### ISSUE THREAD

**Issue by N-Coder** [ogdf/ogdf#53]
Sometimes you need a NodeArray that doesn't assign a value to every node, but only to some of them. For value objects whose lifecycle is managed externally (e.g. `NodeElement`, `EdgeElement`, and so on), this can easily be realized using raw pointers (which is also what happens when using `node`, `edge`, ...). If you're responsible of creating and destroying the values yourself, wrapping those in a `std::unique_ptr` for storage in the array would be a good solution, as otherwise you might easily forget to delete an object stored by its raw pointer. Here's a simplified example:
```c++
#include <ogdf/basic/NodeArray.h>
#include <ogdf/decomposition/StaticPlanarSPQRTree.h>
#include <ogdf/basic/graph_generators/randomized.h>
#include <memory>

using namespace ogdf;

int main() {
    Graph graph1;
    node n = graph1.newNode();
    NodeArray<std::unique_ptr<StaticPlanarSPQRTree>> array(graph1);
    Graph graph2;
    randomBiconnectedGraph(graph2, 20, 40);
    array[n] = std::make_unique<StaticPlanarSPQRTree>(graph2);
}
```
In my specific case, I wanted to annotate each `BComp` node of a `BCTree` with its respective `StaticPlanarSPQRTree`. A different use-case with the same problem would be `DisjointSets`, which can't be reset / reinitialized but only destroyed and reconstructed (which can easily be done using unique pointers). Unfortunately, using `std::unique_ptr` in a `NodeArray` is currently not possible, as compiling the above example using gcc 9.3.1 20200408 yields the following error:
<details>
  <summary><tt>use of deleted function ‘std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&)‘</tt> (click to expand)</summary>

```
In file included from ~/include/ogdf/basic/internal/list_templates.h:35,
                 from ~/include/ogdf/basic/List.h:34,
                 from ~/include/ogdf/basic/GraphList.h:34,
                 from ~/include/ogdf/basic/Graph_d.h:37,
                 from ~/include/ogdf/basic/NodeArray.h:34,
                 from ~/test/test.cpp:1:
~/include/ogdf/basic/Array.h: In instantiation of ‘void ogdf::Array<E, INDEX>::grow(INDEX, const E&) [with E = std::unique_ptr<ogdf::StaticPlanarSPQRTree>; INDEX = int]’:
~/include/ogdf/basic/Array.h:422:43:   required from ‘void ogdf::Array<E, INDEX>::resize(INDEX, const E&) [with E = std::unique_ptr<ogdf::StaticPlanarSPQRTree>; INDEX = int]’
~/include/ogdf/basic/NodeArray.h:314:19:   required from ‘void ogdf::NodeArray<T>::enlargeTable(int) [with T = std::unique_ptr<ogdf::StaticPlanarSPQRTree>]’
~/include/ogdf/basic/NodeArray.h:313:15:   required from here
~/include/ogdf/basic/Array.h:798:3: error: use of deleted function ‘std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = ogdf::StaticPlanarSPQRTree; _Dp = std::default_delete<ogdf::StaticPlanarSPQRTree>]’
  798 |   new (pDest) E(x);
      |   ^~~~~~~~~~~~~~~~
In file included from /usr/include/c++/9/memory:80,
                 from ~/test/test.cpp:4:
/usr/include/c++/9/bits/unique_ptr.h:414:7: note: declared here
  414 |       unique_ptr(const unique_ptr&) = delete;
      |       ^~~~~~~~~~
In file included from ~/include/ogdf/basic/internal/list_templates.h:35,
                 from ~/include/ogdf/basic/List.h:34,
                 from ~/include/ogdf/basic/GraphList.h:34,
                 from ~/include/ogdf/basic/Graph_d.h:37,
                 from ~/include/ogdf/basic/NodeArray.h:34,
                 from ~/test/test.cpp:1:
~/include/ogdf/basic/Array.h: In instantiation of ‘void ogdf::Array<E, INDEX>::initialize(const E&) [with E = std::unique_ptr<ogdf::StaticPlanarSPQRTree>; INDEX = int]’:
~/include/ogdf/basic/Array.h:379:3:   required from ‘void ogdf::Array<E, INDEX>::init(INDEX, INDEX, const E&) [with E = std::unique_ptr<ogdf::StaticPlanarSPQRTree>; INDEX = int]’
~/include/ogdf/basic/NodeArray.h:318:17:   required from ‘void ogdf::NodeArray<T>::reinit(int) [with T = std::unique_ptr<ogdf::StaticPlanarSPQRTree>]’
~/include/ogdf/basic/NodeArray.h:317:15:   required from here
~/include/ogdf/basic/Array.h:856:4: error: use of deleted function ‘std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = ogdf::StaticPlanarSPQRTree; _Dp = std::default_delete<ogdf::StaticPlanarSPQRTree>]’
  856 |    new(pDest) E(x);
      |    ^~~~~~~~~~~~~~~
In file included from /usr/include/c++/9/memory:80,
                 from ~/test/test.cpp:4:
/usr/include/c++/9/bits/unique_ptr.h:414:7: note: declared here
  414 |       unique_ptr(const unique_ptr&) = delete;
      |       ^~~~~~~~~~
gmake[3]: *** [CMakeFiles/test.dir/build.make:63: CMakeFiles/test.dir/test.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:80: CMakeFiles/test.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:87: CMakeFiles/test.dir/rule] Error 2
gmake: *** [Makefile:118: test] Error 2
```
</details>

Not copying unique pointers from arbitrary lvalues is intentional:
```c++
// Disable copy from lvalue.
unique_ptr(const unique_ptr&) = delete;
```
But here, we don't want to construct it from an arbitrary value. The default `NodeArray::m_x` is always `nullptr`, but the compiler doesn't see this and thus can't use the well defined `unique_ptr(nullptr_t)` constructor. Another valid solution would be using the default constructor, as `std::unique_ptr` is default constructible, but not copy constructible.

The ogdf `Array` itself works in this case and the following compiles alright:
```
Array<std::unique_ptr<StaticPlanarSPQRTree>> array(100);
Graph graph2;
randomBiconnectedGraph(graph2, 20, 40);
array[50] = std::make_unique<StaticPlanarSPQRTree>(graph2);
```
Adding `array.resize(200, nullptr);` again yields the above error, while using `array.resize(200);` works fine. Unfortunately, `NodeArray` is hard-wired to use the former. So my suggestion would be adding a second type of `NodeArray` that has no default value and always uses the `Array` methods invoking the default constructor. If that sounds good to you, I'd be happy to make a PR for that.

**Comment by sbeyer** [comment]
Thanks for pointing this issue out. I am surprised this does not work, or that no-one has ever stumbled over this issue before. I also would have expected that `NodeArray` uses the default constructor when no default value isexplicitly given (but, I think, I never tried that myself).

For your proposed solution: What do you mean by
> adding a second type of `NodeArray`

?

**Comment by N-Coder** [comment]
I meant that the most simple solution would be dividing `NodeArray` up into two classes: 
- `CopyConstructingNodeArray<T>` that has a member variable `T m_x` for the default value and uses it to call the copy-constructing `Array::resize(new_size, m_x)` function, exactly as it is done right now in `NodeArray`
- `DefaultConstructingNodeArray<T>` that has no such member variable and directly calls the default-constructing `Array::resize(new_size)` function

For backwards compatibility, you could also alias `NodeArray` to `CopyConstructingNodeArray` (or come up with an entirely different, better naming scheme).

An other way could be using [`std::is_default_constructible`](https://en.cppreference.com/w/cpp/types/is_default_constructible) and [`std::is_copy_constructible`](https://en.cppreference.com/w/cpp/types/is_copy_constructible) and specializing `NodeArray` differently depending on the properties of the template variable. A similar case might be explained [here](https://akrzemi1.wordpress.com/2015/03/02/a-conditional-copy-constructor/), where a Wrapper only has a copy constructor if the wrapped type has one. This has the advantage of only having one user-visible class and automatically choosing the right one, but also makes it impossible for the user to choose between using the default and copy constructor if both are available.

An even more advanced solution could maybe make the signature of the desired constructor part of the template, yielding a C++11 [variadic template](https://en.cppreference.com/w/cpp/language/parameter_pack). We would thus declare `template<class ValueType, class ... ValueCtorTypes> NodeArray` and use
- `NodeArray<MyClass>` to use the default constructor
- `NodeArray<MyClass, const MyClass&>` to use the copy constructor
- `NodeArray<MyClass, int>` to use the `MyClass` constructor that takes a single `int` argument
- `NodeArray<MyClass, node, node>` to use the `MyClass` constructor that takes two `nodes`
- ...

We can then implement the functionality for automatically choosing the right implementation using an alias, while still allowing advanced users to choose themselves. A simplified example how this could look like can be found [here](https://github.com/N-Coder/cpp-variadic-array/blob/master/Array.h). The repository also contains some examples for usage in test.cpp (and the respective output in out.txt); the other two header files are scaffolding for the test. Implementing this was actually quite fun, while this simple implementation should also already cover all above use-cases. :slightly_smiling_face:
The only downside is that the error messages when the class is used wrongly are somewhat hard to read, as it is common when templates are involved. As none of this is weird magic and the user-interface is pretty simple, having this documented and maybe adding a suitable static_assert should make this no worse than before.
So what do you think about this approach?

Side note: Is there a reason why `AdjEntryArray`, `ClusterArray`, `EdgeArray`, `FaceArray`, `NodeArray` are all pretty similar but share no code? Instead of fixing this for each class separately, some common code could probably be re-used by each concrete class. Actually having a generic `AnnotatedArray` base class would be cool, as I also need to annotate stuff in my own (growable, int-indexed) data structure... 
If any of this sounds good to you, I'd be glad to help with the implementation.
