### ISSUE TITLE
UML Diagram 

### ISSUE THREAD

**Issue by iamAzeem** [ogdf/ogdf#58]
Hi,

I'm trying to create and draw a complete UML class diagram using OGDF?
I've gone through the documentation, code on GitHub including tests, some online articles, and built a few sample diagrams.

According to the Optional Parameters of the Sugiyama Layout:
> The options `alignBaseClasses` and `alignSiblings` are only relevant for laying out mixed-upward graphs, where directed edges are interpreted as generalizations and undirected edges as associations in a UML class diagram.

Generalization = directed edge
Association = undirected edge

Can it draw other different shapes for edges such as inheritance, aggregation, composition, etc.?

And, is there a way to represent a class itself with name, attributes, and methods with visibility and multiplicity for relations?

If someone could point in the right direction and to resources, code samples, or share ideas on how to go about it, that would be very helpful.

Thanks!

**Comment by sbeyer** [comment]
Unfortunately, I have to say that I have no idea about OGDF's UML capabilities. I think they are somewhat available but mostly half-baked, perceived as legacy code by most of the recent active developers and hence planned to be removed sooner or later. Based on this, I wouldn't recommend OGDF to render UML (maybe for the layouting, but I don't know if it's then harder to merge layouting and display).

**Comment by iamAzeem** [comment]
@sbeyer: Thank you! I suspected the same after looking at the source code. Regards.
