### ISSUE TITLE
Drawing many planar graphs with the same layout

### ISSUE THREAD

**Issue by maxtremblay** [ogdf/ogdf#71]
Hello,

I have a list of planar graphs with the same number of vertices. I would like to draw them by using the same positions for the vertices across graphs.

In [PlanarizationGridLayout Class Reference](https://ogdf.uos.de/doc/classogdf_1_1_planarization_grid_layout.html#aaf61d6c8ed5c79a5247b6841d68b6387), it mentions that "If the planarization layout algorithm shall be used for simultaneous drawing, you need to define the different subgraphs by setting the subgraphs option."

However, I have no idea how to achieve that. It doesn't seem to be documented. Or maybe I am completely missing it.

**Comment by milsen** [comment]
The documentation is indeed confusing/misleading. I'm not very familiar with the respective classes, but looking at the code, I doubt that `PlanariazationGridLayout` is even capable of simultaneous drawing. `PlanarizationLayout`, however, looks like it is.

Maybe the classes in `ogdf/simultaneous/` might help you to achieve what you want–in particular `SimDraw`, `SimDrawCreator` and `SimDrawCaller::callPlanarizationLayout()`.
As a side note, there also exists `PlanarizationLayout::callSim()` which uses the `subGraphBits` of a `GraphAttributes` object to determine the graph that an edge belongs to.

**Comment by maxtremblay** [comment]
Hey. Thanks a lot for the answer. I didn't know the SimDraw stuff. Really useful in my case :rocket:
